
import { GoogleGenAI, Modality } from "@google/genai";
import type { Tribe } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const fileToGenerativePart = (base64Data: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64Data,
      mimeType
    },
  };
};

export const changeClothes = async (
  originalImageBase64: string,
  mimeType: string,
  tribe: Tribe
): Promise<string> => {
  try {
    const imagePart = fileToGenerativePart(originalImageBase64, mimeType);
    const textPart = {
      text: `In this image of a person, realistically replace the clothes they are wearing with ${tribe.promptDescription}. It is very important to preserve the original person's face, hair, posture, and the background of the image. Only change the clothing.`,
    };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [imagePart, textPart],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
};
